#!/usr/bin/env bash
# Getting the record and destination for a sub domain(s)

if [[ $# -eq 2 ]]; then
  subdom=$2.$1
  dig $subdom | awk '$0==";; ANSWER SECTION:" {f=1; next}!NF {f=0;}f {split ($1, a, "."); print "The subdomain", a [1], "is a", $4, "record and points to", $5}'
else
  dig www.$1 | awk '$0==";; ANSWER SECTION:" {f=1; next}!NF {f=0;}f {split ($1, a, "."); print "The subdomain", a [1],
 "is a", $4, "record and points to", $5}'
  dig lb-01.$1 | awk '$0==";; ANSWER SECTION:" {f=1; next}!NF {f=0;}f {split ($1, a, "."); print "The subdomain", a [1], "is a", $4, "record and points to", $5}'
  dig web-01.$1 | awk '$0==";; ANSWER SECTION:" {f=1; next}!NF {f=0;}f {split ($1, a, "."); print "The subdomain", a [1], "is a", $4, "record and points to", $5}'
  dig web-02.$1 | awk '$0==";; ANSWER SECTION:" {f=1; next}!NF {f=0;}f {split ($1, a, "."); print "The subdomain", a [1], "is a", $4, "record and points to", $5}'
fi
