#!/usr/bin/env bash
# Install nginx and configure it
apt-get -y update && apt-get -y install nginx;

SERVER_HTML_CONTENT="<h1>Hello World! from server.html</h1>"

echo "server {
    listen 80;
    location / {
        root /var/www/html;
        index index.html index.htm;
        try_files \$uri \$uri/ /index.html;
        if (!-f \$uri) {
                rewrite ^ /server.html break;
        }
    }
}" > /etc/nginx/sites-available/web-01;

mkdir -p /var/www/html
echo "Hello World!" >> /var/www/html/index.html
echo "$SERVER_HTML_CONTENT" > /var/www/html/server.html
ln -s /etc/nginx/sites-available/web-01 /etc/nginx/sites-enabled/web-01
nginx -t
service nginx restart
