#!/usr/bin/env bash
# Install nginx and configure it with a 301
apt-get -y update && apt-get -y install nginx;
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
