#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
SERVER_CONFIG=\
"server {
    listen 80;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}
"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

service nginx restart
