#!/usr/bin/env bash
# Process and PID file fam

echo $$ > /var/run/myscript.pid

sigterm_handler() {
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}
trap 'sigterm_handler' SIGTERM

sigint_handler() {
	echo "Y U no love me?!"
	exit 0
}
trap 'sigint_handler' SIGINT

sigquit_handler() {
	rm /var/run/myscript.pid
	exit 0
}
trap 'sigquit_handler' SIGQUIT

i=1
while ((i == 1)); do
	echo "To infinity and beyond"
	sleep 2
done
