#!/usr/bin/env bash
# Managing process management

PID_FILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start() {
        $SCRIPT &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
}

stop() {
        kill "$(cat $PID_FILE)"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped"
}

restart() {
	kill "$(cat $PID_FILE)"
	rm -f "$PID_FILE"
	$SCRIPT &
	echo $! > "$PID_FILE"
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
