#!/usr/bin/env bash
# Managing process management

PID_FILE="/var/run/my_process.pid"
SCRIPT="./manage_my_process"

start() {
    if [ -e "$PID_FILE" ]; then
        echo "manage_my_process is already running."
    else
        $SCRIPT &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -e "$PID_FILE" ]; then
        kill "$(cat $PID_FILE)"
        rm -f "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    if [ -e "$PID_FILE" ]; then
	kill "$(cat $PID_FILE)"
	rm -f "$PID_FILE"
    else
	echo "manage_my_process is not running."
    fi
    if [ -e "$PID_FILE" ]; then
	echo "manage_my_process is already running."
    else
	$SCRIPT &
	echo $! > "$PID_FILE"
    fi
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
