#!/usr/bin/env bash
# Installing UFW with custom configurations
sudo apt install -y ufw
sudo ufw --force enable
sudo ufw default deny incoming
sudo ufw allow 80
sudo ufw allow 443
sudo ufw allow 22
sudo service ufw restart
